#!/bin/bash
bcftools query -f '[\t%GQ]\n' chr1A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ1
bcftools query -f '[\t%GQ]\n' chr2A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ2
bcftools query -f '[\t%GQ]\n' chr3A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ3
bcftools query -f '[\t%GQ]\n' chr4A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ4
bcftools query -f '[\t%GQ]\n' chr5A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ5
bcftools query -f '[\t%GQ]\n' chr6A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ6
bcftools query -f '[\t%GQ]\n' chr7A.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ7
bcftools query -f '[\t%GQ]\n' chr1A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ8
bcftools query -f '[\t%GQ]\n' chr2A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ9
bcftools query -f '[\t%GQ]\n' chr3A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ10
bcftools query -f '[\t%GQ]\n' chr4A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ11
bcftools query -f '[\t%GQ]\n' chr5A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ12
bcftools query -f '[\t%GQ]\n' chr6A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ13
bcftools query -f '[\t%GQ]\n' chr7A.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ14
bcftools query -f '[\t%GQ]\n' chr1B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ15
bcftools query -f '[\t%GQ]\n' chr2B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ16
bcftools query -f '[\t%GQ]\n' chr3B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ17
bcftools query -f '[\t%GQ]\n' chr4B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ18
bcftools query -f '[\t%GQ]\n' chr5B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ19
bcftools query -f '[\t%GQ]\n' chr6B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ20
bcftools query -f '[\t%GQ]\n' chr7B.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ21
bcftools query -f '[\t%GQ]\n' chr1B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ22
bcftools query -f '[\t%GQ]\n' chr2B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ23
bcftools query -f '[\t%GQ]\n' chr3B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ24
bcftools query -f '[\t%GQ]\n' chr4B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ25
bcftools query -f '[\t%GQ]\n' chr5B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ26
bcftools query -f '[\t%GQ]\n' chr6B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ27
bcftools query -f '[\t%GQ]\n' chr7B.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ28
bcftools query -f '[\t%GQ]\n' chr1D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ29
bcftools query -f '[\t%GQ]\n' chr2D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ30
bcftools query -f '[\t%GQ]\n' chr3D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ31
bcftools query -f '[\t%GQ]\n' chr4D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ32
bcftools query -f '[\t%GQ]\n' chr5D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ33
bcftools query -f '[\t%GQ]\n' chr6D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ34
bcftools query -f '[\t%GQ]\n' chr7D.1.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ35
bcftools query -f '[\t%GQ]\n' chr1D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ36
bcftools query -f '[\t%GQ]\n' chr2D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ37
bcftools query -f '[\t%GQ]\n' chr3D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ38
bcftools query -f '[\t%GQ]\n' chr4D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ39
bcftools query -f '[\t%GQ]\n' chr5D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ40
bcftools query -f '[\t%GQ]\n' chr6D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ41
bcftools query -f '[\t%GQ]\n' chr7D.2.raw.vcf | awk '{printf "%s\n",$2}' > onlyGQ42

